# Generated by Django 2.2.5 on 2019-10-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', help_text='会社名', max_length=30, verbose_name='会社名')),
                ('job_name', models.CharField(default='', help_text='仕事内容', max_length=100, verbose_name='仕事内容')),
                ('link_url', models.CharField(default='', help_text='詳細リンク', max_length=150, verbose_name='詳細リンク')),
                ('nearest_station', models.CharField(default='', help_text='住所', max_length=50, null=True, verbose_name='住所')),
                ('longitude', models.CharField(default='', help_text='経度', max_length=20, null=True, verbose_name='経度')),
                ('latitude', models.CharField(default='', help_text='緯度', max_length=20, null=True, verbose_name='緯度')),
                ('source', models.CharField(help_text='出所', max_length=20, verbose_name='出所')),
                ('create_data', models.CharField(help_text='スクロール時間', max_length=30, verbose_name='スクロール時間')),
            ],
            options={
                'verbose_name': 'クローラデータ',
                'verbose_name_plural': 'クローラデータ',
            },
        ),
    ]
