# Generated by Django 2.2.5 on 2019-10-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerdata',
            name='annual_income_max',
            field=models.CharField(default=0, help_text='最高提示年収', max_length=10, null=True, verbose_name='最高提示年収'),
        ),
        migrations.AddField(
            model_name='crawlerdata',
            name='annual_income_min',
            field=models.CharField(default=0, help_text='最低提示年収', max_length=10, null=True, verbose_name='最低提示年収'),
        ),
        migrations.AddField(
            model_name='crawlerdata',
            name='occupation',
            field=models.CharField(default='営業', help_text='職種', max_length=50, verbose_name='職種'),
        ),
        migrations.AddField(
            model_name='crawlerdata',
            name='published_time',
            field=models.CharField(default='', help_text='サイト内での掲載時間', max_length=100, null=True, verbose_name='サイト内での掲載時間'),
        ),
    ]
